### PR TITLE
Stylelint

### PR DESCRIPTION
**Pull request by tannerhodges**
Switching from [scss-lint](https://github.com/brigade/scss-lint) to [stylelint](https://stylelint.io).

## Rules

I did my best to match the [rules](https://stylelint.io/user-guide/rules/) we were using before:

- Property order is handled by [stylelint-config-property-sort-order-smacss](https://github.com/cahamilton/stylelint-config-property-sort-order-smacss) ([see full property list](https://github.com/cahamilton/css-property-sort-order-smacss/blob/master/index.js))
- The rest of the config is outlined in `.stylelintrc`.

@glennabaron There are a few rules I'd like to include but want to run by you first. We can chat whenever. Here's a list in the meantime:

- [at-rule-empty-line-before](https://stylelint.io/user-guide/rules/at-rule-empty-line-before)
- [declaration-block-single-line-max-declarations](https://stylelint.io/user-guide/rules/declaration-block-single-line-max-declarations)
- [declaration-colon-newline-after](https://stylelint.io/user-guide/rules/declaration-colon-newline-after)
- [max-nesting-depth](https://stylelint.io/user-guide/rules/max-nesting-depth)
- [selector-max-compound-selectors](https://stylelint.io/user-guide/rules/selector-max-compound-selectors)
- [selector-max-specificity](https://stylelint.io/user-guide/rules/selector-max-specificity)

### Uninstall scss-lint

- `gem uninstall scss_lint`
- Sublime Text > Package Control: Remove Package > SublimeLinter-contrib-scsslint

### Install stylelint

- `npm install -g stylelint`
- Install SublimeLinter packages*:
    - Sublime Text > Package Control: Install Package > SublimeLinter
    - Sublime Text > Package Control: Install Package > SublimeLinter-contrib-stylelint
- Then `yarn add stylelint-config-property-sort-order-smacss` for each project you want to lint

*Plugins for other text editors are listed [here](https://stylelint.io/user-guide/complementary-tools/#editor-plugins).

## Sublime Preferences

To automatically lint and show errors when you save a file:

- Sublime Text > Preferences > Package Settings > SublimeLinter > Settings - User
- Add these options:

```json
{
  "user": {
    "lint_mode": "load/save",
    "show_errors_on_save": true,
  }
}
```

## Using the CLI

Use [the stylelint CLI](https://stylelint.io/user-guide/cli) to quickly scan whole projects:

```
stylelint resources/assets/sass/**/*.scss
```

### CODE REVIEW

**Comment by glennabaron** [comment]
As discussed IRL: 

- ✅ at-rule-empty-line-before
- ✅ (3) declaration-block-single-line-max-declarations
- ✅ (`always-multi-line`) declaration-colon-newline-after
- ✅ (3 - ignore @includes) max-nesting-depth
- ✅ (5) selector-max-compound-selectors
- ❌ selector-max-specificity

**Comment by tannerhodges** [comment]
Ack, looks like [at-rule-empty-line-before](https://stylelint.io/user-guide/rules/at-rule-empty-line-before) throws errors for Sass statements like `@if`, etc: 

at-rule-empty-line-before throws errors for Sass statements like @if

Going to remove that one but add the rest.

**Comment by tannerhodges** [comment]
Similar problem with [max-nesting-depth](https://stylelint.io/user-guide/rules/max-nesting-depth): 

You have to ignore entire rules (e.g., `@include`) so we can't limit the ignore option to specific mixins (e.g., `@include mq(…)`).

And even if we could, that would ignore the entire block. So ignoring `@include mq(…)` would allow any amount of nesting in that block.

Going to keep things simple and use a flat number. Setting to 5 for now.

**Comment by tannerhodges** [comment]
@glennabaron Styleint options are updated and ready to review.

**Review by glennabaron — APPROVED** [review]

**Pull request merged**
